### ISSUE TITLE
SourceAddressAdapter not working for BaseHTTPRequestHandler

### ISSUE THREAD

**Issue by crazy-canux** [requests/toolbelt#258]
Trying to bind client address.
 
```
   s = requests.Session()
    s.mount('http://', SourceAddressAdapter(192.168.1.1))
    s.mount('https://', SourceAddressAdapter(192.168.1.1))

    response = s.post("http://"+serverport, stream=True,
                      data=json.dumps(req), headers=headers, timeout=10, verify=False)
    log.warning("peer: {}".format(response.raw._fp.fp._sock.getpeername()))
    log.warning("sock: {}".format(response.raw._fp.fp._sock.getsockname()))
```

But BaseHTTPRequestHandler.client_address can't get the specify address.
`BaseHTTPRequestHandler.client_address
`

This is my network config:
```
ens160    Link encap:Ethernet  HWaddr 00:50:56:b4:b8:8c
          inet addr:10.103.239.44  Bcast:10.103.239.255  Mask:255.255.254.0
          inet6 addr: fe80::250:56ff:feb4:b88c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3117203 errors:0 dropped:255 overruns:0 frame:0
          TX packets:655501 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1734665414 (1.7 GB)  TX bytes:132262043 (132.2 MB)

ens192    Link encap:Ethernet  HWaddr 00:50:56:b4:f5:82
          inet6 addr: fe80::250:56ff:feb4:f582/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3095192 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1649630 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:822134256 (822.1 MB)  TX bytes:228842319 (228.8 MB)

lan0      Link encap:Ethernet  HWaddr 00:50:56:b4:f5:82
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::250:56ff:feb4:f582/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4721443 errors:0 dropped:6 overruns:0 frame:0
          TX packets:7816381 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1172372654 (1.1 GB)  TX bytes:2362740308 (2.3 GB)
```

**Comment by sigmavirus24** [comment]
`BaseHTTPRequestHandler` is part of `http.server` which is not part of, or affected by, this library.

Can you please share more about:

- what you're using (versions of Requests, the toolbelt, python, etc.)
- what you're expecting to see and where
- what `BaseHTTPRequestHandler` has to do with all of this

**Comment by crazy-canux** [comment]
requests (2.18.4)
requests-toolbelt (0.8.0)
python: 2.7.12

`BaseHTTPRequestHandler`  come from "import BaseHTTPServer.

I use request and toolbelt to post message.
The backend use library  BaseHTTPServer.
I want to use toolbelt to specify client ip address.
But, the backend didn't get the specify ip address with `BaseHTTPRequestHandler.client_address`

**Comment by sigmavirus24** [comment]
So, to the best of my knowledge (I haven't used it in quite a while) the source address adapter still works. If there's a bug, I think it'll probably end up being in urllib3 since we're just making it easier to use the functionality that urllib3 provides.

Beyond that, there's too many other pieces here for us to be able to help debug this without a very tiny reproducible case and there's still far too much information missing. For example, it's possible that you're actually using `192.168` IP addresses which I'd be suspect of working. It's also possible there's a proxy or router of sorts between your Requests client and the BaseHTTPServer which means that the `client_adress` isn't actually set appropriately. It's possible that 2.7.12 has some bug in the implementation or doesn't take into account forwarded IP addresses from proxy/routers.  There's not enough here that shows there's a bug in Requests or the toolbelt.
