### ISSUE TITLE
Dump does not support generators as request bodies

### ISSUE THREAD

**Issue by Checkroth** [requests/toolbelt#277]
I'm trying to dump the raw request for a utility that fires off a request from a generator.

`dump.dump_all` appears to put a string-converted error message in place of the request body when I try to dump the request:

```
b'< POST /speech-to-text HTTP/1.1\r\n< Host: mysite.com\r\n< User-Agent: python-requests/2.22.0\r\n< Accept-Encoding: gzip, deflate\r\n< Accept: */*\r\n< Connection: keep-alive\r\n< Transfer-Encoding: chunked\r\n< \r\n<< Request body is not a string-like type >>\r\n> 
```

I don't know if it would be possible to dump the body of a generator after the fact, but I'm also not sure if dumping a python error message with the request is expected functionality. If generator based requests were going to be dumped I think it would have to be implemented on a dump request ( #206  ) utility that captures outgoing data as its sent, rather than after-the-fact.

**Comment by sigmavirus24** [comment]
We'd have to rewind a generator to do this. We also don't even have the ability to capture the data as it's sent without swapping out the socket library directly and teeing the data. That's not even remotely reasonable for all implementations of Python that Requests supports. Because of how much urllib3 actually does for Requests, there's no good way to intercept this.
