### ISSUE TITLE
Dump line break is not OS dependant

### ISSUE THREAD

**Issue by rmescandon** [requests/toolbelt#285]
When using utils/dump module to print out http messages to a file, I see that line breaks in Ubuntu are the ones belonging to Windows ('\r\n' instead of '\n')

**Comment by sigmavirus24** [comment]
That's the actual HTTP protocol definition which is OS independent. If printing those is a problem for you, perhaps consider a different solution since this is trying to provide as accurate as possible a representation of what bytes are going over the wire or being received over the wire to the best of the library's ability.

**Comment by rmescandon** [comment]
Good catch. Thought it was a mistake. Thanks
