### ISSUE TITLE
Does StreamingIterator take fileobjects and iterate over the file in parts ?

### ISSUE THREAD

**Issue by pghole** [requests/toolbelt#311]
My usecase is as below
The api which I use for uploading my file, has a limitation uploading files of only 2MB data per requests. Hence, I need to split my file(of total 10MB) in 2MB parts and send them individually to the api. (making 5 requests to api)

I came across this package and passed my fileobj in the streamingIterator as follows
StreamingIterator((2000000 , fileobj)  - as it will read only 2MB from the file, which works fine and I get my first part uploaded.

Now, how to upload the second, third etc. parts. Does this library support picking data from fileobjs. in offsets or does it always begin from the start ? Any solution for my issue using requests-toolbelt ?

**Comment by sigmavirus24** [comment]
`StreamingIterator` uses the size only to inform Requests of what the size is. It will continue to read from the object and if you are not limiting your object yourself, you then will send more than the stated `Content-Length`.

You can probably plagiarize a great deal from this library to achieve what you want to achieve. The MultipartEncoder in particular does a lot of offset math and tracking in order to accomplish something reasonable. It also uses a small in-memory buffer to work properly. I know of nothing that does what you want though.

The general shape I would suggest is a 

```
class FileWrapper:
    def __init__(self, fileobj, start_offset, max_amt_to_read):
        self.read_already = 0
        self.fd = fileobj
        self.start = start_offset
        self.max_read = max_amt_to_read

   def __len__(self) -> int:  # this will let Requests magic it's way to a `Content-Length` header
       return self.max_read 

   def read(self, size=-1) -> bytes:
       if self.read_already >= self.max:
            return b''
       current_position = self.fd.tell()
       if current_position != self.start + self.read_already:
            self.fd.seek(0, self.start + self.read_already)
       if size > 0:
            size = max(size, self.max - self.read_already)
            to_return = self.fd.read(size)
            self.read_already += size
       elif size == 0:
            return b''
       else:
            self.read_already = self.max
            return self.fd.read(self.max)
       return to_return
```

Obviously I just spat that out and didn't test it, but something like that should work. It should even (assuming you create each wrapper in a thread) maintain the proper position but it's certianly not threadsafe. You'll want to use https://docs.python.org/3/library/threading.html#rlock-objects but I'm not doing all of that for you.

**Comment by pghole** [comment]
@sigmavirus24 Thanks for responding. I will try doing this way.
