### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by loucadufault** [requests/toolbelt#348]
Not sure why, but the documentation for this package on https://toolbelt.readthedocs.io/en/latest/ seems to be trailing the latest release (0.10.1). As such, there are bugs such as this one: #259 that are [still present in the docs](https://toolbelt.readthedocs.io/en/latest/sessions.html#requests_toolbelt.sessions.BaseUrlSession) years later. 

Is this a known issue?

**Comment by pquentin** [comment]
I'm aware of this, but need @sigmavirus24 to give me (`pquentin`) access to the docs for me to fix it.

**Comment by sigmavirus24** [comment]
Sent you the invite @pquentin .

I suspect I'll need to elevate your privileges on the repo too in order to settle this, but I'm still mostly operating from a phone these days. Let me know if you need additional permissions

**Comment by pquentin** [comment]
@loucadufault Thanks to @sigmavirus24, https://toolbelt.readthedocs.io/en/latest/ is now up-to-date.

However, releases won't have any effect as the fix was a manual build and the GitHub webhook is gone. I tried adding it in https://readthedocs.org/dashboard/toolbelt/integrations/ but I don't have the necessary GitHub permissions. @sigmavirus24 Would you mind adding it or figuring out how to elevate my GitHub privileges? (The next step will be to configure Read the Docs to build on pull requests.)

**Comment by pquentin** [comment]
Thanks, the integration is in place, closing.
